include:
  - board: xiao_ble//zmk
    shield: forager_dongle
    snippet: studio-rpc-usb-uart
  - board: xiao_ble//zmk
    shield: forager_left rgbled_adapter
  - board: xiao_ble//zmk
    shield: forager_left_central rgbled_adapter
  - board: xiao_ble//zmk
    shield: forager_right rgbled_adapter
  - board: xiao_ble//zmk
    shield: settings_reset
